### ISSUE TITLE
set up continuous deployment of configuration

### ISSUE THREAD

**Issue by JJediny** [18F/newrelic-terraform#16]
## Implementation steps
- [x] finalize and merge - https://github.com/18F/newrelic-terraform/pull/8
- [x] setup API key within circleci
- [x] use circleci to test all terraform scans and pre-steps
- [x] use circleci to continuously apply changes to domain monitoring

## Acceptance Criteria

- [x] Terraform configuration is `apply`d on merge

**Comment by adborden** [comment]
@JJediny I think this is about done. Not sure what this task was about. Would that be the drift workflow we were talking about? I guess I should've included it :D
> use circleci to continuously apply changes to domain monitoring

**Comment by afeld** [comment]
That's the Synthetics piece.

**Comment by JJediny** [comment]
alerts and infra are being manually managed by teams via the UI, the merged #22 addresses and closes this issue
