### ISSUE TITLE
get Synthetics dashboard green

### ISSUE THREAD

**Issue by afeld** [18F/newrelic-terraform#24]
## Background Information

[Our TTS-wide Synthetics dashboard](https://one.newrelic.com/-/09MR2X334QY) has a handful of domains whose checks have been failing for a while. Some of these may be false negatives, in the request needs to send a special header or something in order to get a successful status code. Some may be true negatives, in that the site is no longer live and the `Production Status` needs to be updated in the [GSA websites inventory](https://docs.google.com/spreadsheets/d/1OBO6g7_OsVBv0vG8WSCI6L2FD_iRh3A7a_6eQWj2zLE/edit?ts=6025575d#gid=2013137748).

## Implementation Steps

- [ ] Inventory updated
- [ ] Synthetics alerts updated
- [ ] @afeld Unmute #tts-tech-portfolio-alerts
- [ ] Add handling of uptime monitoring failures to OpsRotation

## Acceptance Criteria

- [ ] We aren't seeing any false negatives or true negatives (aside from unintended downtime) in the dashboard
