### ISSUE TITLE
confirm if Synthetics alerts would be useful to program teams

### ISSUE THREAD

**Issue by afeld** [18F/newrelic-terraform#25]
## Background Information

We have the monitoring set up for all TTS subdomains, but never set up the alerting to go to program teams. We should confirm this would be useful to program teams. Perhaps with https://github.com/18F/tts-tech-portfolio/issues/1378, we send out a survey asking things like:

- Do you have uptime monitoring set up for your system?
- Would you welcome uptime monitoring provided by the Tech Portfolio?
- How would you want to be notified of a site going down?

## Implementation Steps

- [ ] Survey created
- [ ] Sent to teams
- [ ] Follow-up task created for implementing the alerts (if applicable)

## Acceptance Criteria

- [ ] We have a sense of what Minimum Viable uptime monitoring would be useful for teams, if at all

**Comment by ryanwoldatwork** [comment]
@JJediny,

After the next New Relic update, we'll have the latest list of sites.
I've created the Survey above in Touchpoints. After you sign up, I can add you to the form.
